alias ..='cd ..'
alias Gc='git clone $1'
alias b='cd -'
alias bashrc='nano /data/data/com.termux/files/usr/etc/bash.bashrc'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias fn='find /data/data/com.termux/files/ -name '
alias grep='grep --color=auto'
alias l='ls -alt'
alias la='ls -A'
alias ll='ls -alF'
alias ls='ls --color=auto'
alias p='ping'
alias py='python -Bq'
alias serv='python -m http.server'
alias upd='apt update -y'
alias upg='apt upgrade -y'
alias cls="clear"
